config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'fact_cats', to: 'fact_cats#index', as: 'fact_cats'
  get 'fact_cats_favorite', to: 'fact_cats#favorite', as: 'fact_cats_favorite'
  post 'fact_cats/:fact_cat_id/increment_click_count', to: 'fact_cats#increment_click_count', as: 'fact_cats_count_click'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/fact_cat.rb
class FactCat < ApplicationRecord
    has_and_belongs_to_many :users
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, authentication_keys: [:username]
  validates :username, presence: true, uniqueness: { case_sensitive: false }
  has_and_belongs_to_many :fact_cats

  def email_required?
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    def after_sign_in_path_for(resource)
        root_path
    end

    protected

        def configure_permitted_parameters
            added_attrs = [:username, :email, :password, :password_confirmation]
            devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
            devise_parameter_sanitizer.permit :sign_in, keys: [:username, :password]
            devise_parameter_sanitizer.permit :account_update, keys: added_attrs
        end
end

app/controllers/fact_cats_controller.rb
require 'httparty'

class FactCatsController < ApplicationController
    include HTTParty;

    def index
        @fact_cats = FactCat.all
        get_fact_cat(2)
        render 'index', locals: { favorite: true, titulo: 'Nuestros Facts Cats para ti', ranking: false }
    end

    def favorite
        if !current_user
            flash[:error] = 'ups para ver tus favoritos debes estar registrado'
            return redirect_to root_path
        end
        @fact_cats = current_user.fact_cats.uniq
        render 'index', locals: { favorite: false, titulo: 'Tus Fact Cats favoritos', ranking: false}
    end

    def increment_click_count
        return if !current_user || !params[:fact_cat_id]
        fact_cat_id = params[:fact_cat_id]
        fact_cat = FactCat.find(fact_cat_id)
        fact_cat.clicks += 1
        fact_cat.users << current_user
        if fact_cat.save
            flash[:notice] = 'La fact se ha marcado cómo favorita'
            redirect_to root_path
        else
            flash[:error] = 'La fact no se ha podido marcar cómo favorita'
        end
    end

    def get_fact_cat(times_number)

        times_number.times do
            response = HTTParty.get('https://catfact.ninja/fact')

            if response.code == 200
                fact = response.parsed_response['fact']
                length = response.parsed_response['length']
                cat = FactCat.new(fact: fact, length: length)

                if cat.save
                    flash[:notice] = 'facts agregado con éxito!'
                    root_path
                else
                    @error = "Error al guardar el fact: #{cat.errors.full_messages.join(', ')}"
                    erb :error
                end
            @fact = response.parsed_response['fact']
            else
            @error = "Error: #{response.code}"
            end
        end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        # lógica y código para la página de inicio
    end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
   
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
    protected
        def sign_up_params
            params.require(:user).permit(:username)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/fact_cats/index.html.erb
<div class= 'd-flex justify-content-center'>
    <div class="row">
        <div class="col text-center">
            <h2 class="font-weight-bold text-center"><%=titulo%></h2>
        <div/>
        <div class="col border">
            <% if @fact_cats %>
                <table  class="table table-striped">
                    <thead>
                            <% if ranking%>
                                <th>Ranking</th>
                                <th>Facts</th>
                                <th>Marcar favorito</th>
                            <% else %>
                                <th>Facts</th>
                            <% end %>
                        </tr>
                    </thead>
                    <tbody>
                        <% @fact_cats.each_with_index do |fact, index| %>
                            <tr>
                                <% if ranking%>
                                    <td><%= index + 1 %></td>
                                <% end %>
                                <td><%= fact.fact %></td>
                                <% if favorite%>
                                    <td>
                                        <%= button_to fact_cats_count_click_path(fact_cat_id: fact.id), method: :post, class: "btn btn-warning" do %>
                                            <i class="fa fa-star"></i>
                                        <% end %>
                                    </td>
                                <% end %>
                            </tr>
                        <% end %>
                    </tbody>
                </table>
            <% end %>
        <div/>
    <div/>
<div/>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SSCatFacts</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Con estas 2 líneas llamamos a los archivos CSS y Javascript de Bootstrap y demás -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
  </head>

  <body>
    <div class="container-fluid">
      <div class="row fixed-top position-fixed left-0">
         <div class="col-md-2 border h-100">
            <div id="sidebar">
              <header>
                <a href="/">SSCatFacts <i class="fas fa-cat"></i></a>
              </header>
               <% if current_user %>
                  <ul class="nav flex-column flex-fill">
                    <li >
                      <a href="<%= url_for(fact_cats_favorite_path) %>">
                        <i class="zmdi zmdi-view-dashboard"></i> Mis favoritos
                      </a>
                    </li>
                    <li>
                      <a href= "<%= url_for(destroy_user_session_path) %>">
                        <i class="zmdi zmdi-calendar"></i> Cerrar sesión
                      </a>
                    </li>
                  </ul>
                <% end %>
            </div>
          </div>
          <div id = 'content' class="col-md-10">
              <%= yield %>
          </div>
      </div>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div>
    <div>
        <h1 class="font-weight-bold text-center">Bienvenido a SSCatFacts <h1>
        <h3 class="font-weight-normal text-center">
            Aquí podrás aprender más de tu gato a través de nuestros datos o
            <code>#fact</code>.
        </h3>
    </div>
    <% if current_user %>
        <div class="text-center">
            <a href="<%= url_for(fact_cats_path) %>" class="btn btn-primary btn-lg" role="button" aria-disabled="true">!Pincha aqui para conocer más datos! <i class="fas fa-cat"></i></a>
        </div>
        <br>
         <% @fact_cats = FactCat.all.sort_by { |fact_cat| fact_cat.clicks }.reverse.first(5)  %>
         <%= render template: "fact_cats/index", locals: {favorite: true, titulo: 'Facts más populares', ranking: true } %>
    <% else %>
        <h3 class="font-weight-normal text-center">
            ups! no has iniciado sesión
        </h3>
        <div class="text-center">
            <a href="<%= url_for(user_session_path) %>" class="btn btn-primary btn-lg" role="button" aria-disabled="true">Iniciar sesión <i class="fas fa-cat"></i></a>
            <br/>
            <br/>

            <a href="<%= url_for(new_user_session_path) %>" class="btn btn-primary btn-lg" role="button" aria-disabled="true">Registrarse<i class="fas fa-cat"></i></a>
        </div>
    <% end %>
</div>